"""
schemas.py — Pydantic v2 Data Contracts
=========================================
These models define the exact JSON shapes that the automated evaluation
harness expects on both the request and response side.

Why Pydantic?
- FastAPI uses Pydantic models for automatic request parsing and response
  serialisation, giving us free OpenAPI docs and runtime type validation.
- If an incoming request is malformed (wrong field name, wrong type),
  FastAPI automatically returns a clean HTTP 422 — no manual validation code.
- Pydantic v2 is significantly faster than v1 due to its Rust core.
"""

from typing import List, Literal
from pydantic import BaseModel, Field


class Message(BaseModel):
    """
    A single turn in the conversation.

    `role` is a Literal so Pydantic will reject any value other than
    "user" or "assistant" at the boundary — no downstream guard needed.
    """
    role: Literal["user", "assistant"]
    content: str


class ChatRequest(BaseModel):
    """
    Full request body for POST /chat.

    The client sends the *entire* conversation history with every request.
    This is the stateless design: the server never holds session data.
    """
    messages: List[Message] = Field(
        ...,
        description="Complete conversation history, oldest message first."
    )


class RecommendationItem(BaseModel):
    """
    One assessment recommendation returned to the client.

    All three fields are sourced directly from catalog.json.
    The agent layer enforces a URL-integrity check so no hallucinated
    URLs can ever appear in this model.
    """
    name: str        # Exact product name from the catalog
    url: str         # Exact URL from the catalog — never generated by the LLM
    test_type: str   # Single-letter code: A=Ability, P=Personality, K=Knowledge, S=Situational


class ChatResponse(BaseModel):
    """
    Full response body for POST /chat.

    Schema rules (non-negotiable per the evaluation harness):
    - `recommendations` is [] when clarifying, comparing, or refusing.
    - `recommendations` has 1–10 items when a shortlist is committed.
    - `end_of_conversation` is True only when the user is fully satisfied.
    """
    reply: str
    recommendations: List[RecommendationItem] = Field(
        default_factory=list,
        description="Empty list when clarifying/refusing/comparing; 1-10 items when recommending."
    )
    end_of_conversation: bool = False
